# User Settings | Edit there as per required

title: brian4286
url: "https://brian.haun.me"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    brian<span class="faded">4286</span>

email: brian@email.tld
author: brian4286
# This description will show up in google search results
# (for index page) etc.
description: The open notebook of a Unix/Linux Infrastructure Engineer ✦ Cloud Architect ✦ Systems Administration ✦ Solutions Delivery.

# This will what will show against &copy; in the footer
copyright: Brian Haun 2014-2016
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Welcome! This is <span>accent</span>, a mobile friendly theme for Jekyll. The main feature of this
    theme is that you can change the accent color. Refer the
    <a class="underline different-highlight" href="http://ankitsultana.me/accent/documentation.html">
        Documentation
    </a>
    to know how.

permalink: /:title.html


# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Ok who is this guy?

about_footer: true

twitter_username: brian4286
github_username: brian4286
facebook_id: yourusername

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/brian4286.jpg
paginate: 16
paginate_path: "/page/:num"
tracking_id: UA-80969106-1 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/brian4286.jpg" # This will show in facebook thumbnails
twitter_image: "" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
